### ISSUE TITLE
This particular JXL refuses to display as a thumbnail in Directory Opus

### ISSUE THREAD

**Issue by Neltulz** [saschanaz/jxl-winthumb#1]
Most JXLs preview just fine. This particular one does not.  Any clue?

![image](https://user-images.githubusercontent.com/7741742/106605404-7ae62d80-6526-11eb-8079-6c8aa15d90bd.png)

[screenshot0009_GIGA_(JPEGXL_d2_s7).jxl.zip](https://github.com/saschanaz/jxl-winthumb/files/5911353/screenshot0009_GIGA_.JPEGXL_d2_s7.jxl.zip)

**Comment by saschanaz** [comment]
![image](https://user-images.githubusercontent.com/3396686/106614566-cb33ae80-656b-11eb-86f8-19f949d32cae.png)

Weird, works for me 🤔

Could you copy-paste the file and see if the same happens for the new file?

**Comment by Neltulz** [comment]
Maybe I am due for a reboot. 🤷 

![image](https://user-images.githubusercontent.com/7741742/106623907-b559c580-653a-11eb-8f4a-93646d1566b0.png)

**Comment by saschanaz** [comment]
That's... a big customization 👀

Could you test it on regular File Explorer, if it's still available?

**Comment by Neltulz** [comment]
Very interesting.  Yeah, works fine in regular File Explorer.  Wonder why Directory Opus is getting hung up on this JXL.  There are more that it is refusing to display.

I'll look around to see if I can refresh a thumbnail cache for Directory Opus.

**Comment by saschanaz** [comment]
Just to check, could you reduce the preview size in Directory Opus and try copy-pasting again?

**Comment by saschanaz** [comment]
I can't confirm this still happens since Directory Opus is a paid app and I don't intend to pay. Please feel free to reopen if this still happens.
