### ISSUE TITLE
Implement IPropertyStore

### ISSUE THREAD

**Issue by g0blin-NN** [saschanaz/jxl-winthumb#17]
Why does not it show the resolution of the jxl picture?
![Буфер обмена04](https://user-images.githubusercontent.com/66860852/139585919-fd4cf1c4-434b-4e3a-8428-c4b53fa3cd36.png)

**Comment by saschanaz** [comment]
Because no metadata decoder is implemented yet 😬 It's in my TODO, but any help is welcome 😉

**Comment by g0blin-NN** [comment]
I understand. I'll be waiting.

**Comment by saschanaz** [comment]
I'd like to keep this in my backlog though, so reopening.
