### ISSUE TITLE
Will there be any x86 version

### ISSUE THREAD

**Issue by Youxikong** [saschanaz/jxl-winthumb#18]
Some old softwares has only x86 version, it would be better to support those softwares.

**Comment by saschanaz** [comment]
Shouldn't be too hard *if* libjxl supports 32bit build, which I haven't tried yet.

**Comment by saschanaz** [comment]
BTW, which software is still on 32bit x86?

**Comment by Youxikong** [comment]
FenrirFS, is a tag file manager, can preview media file by wic codec and wmp. And there are some picture viewers which are staying on 32bit x86.

**Comment by saschanaz** [comment]
Thanks, that will be useful when testing against 32bit.

**Comment by Youxikong** [comment]
I think [jpegview](https://github.com/sylikc/jpegview) 32bit version is better for testing.

**Comment by saschanaz** [comment]
Closing per https://github.com/saschanaz/jxl-winthumb/issues/22#issuecomment-1796506994.
