### ISSUE TITLE
Support for 32-bit applications

### ISSUE THREAD

**Issue by Niotferdi** [saschanaz/jxl-winthumb#22]
Please add support for 32-bit programs to this software! The only program I need jxl support for doesn't have a 64 bit version.

**Comment by saschanaz** [comment]
Hi, what's the name of the app you are using? 32-bit support should be as easy as a single command, but I need to do some test before uploading the binary.

**Comment by Niotferdi** [comment]
This app is Foobar2000. The 32-bit version does not support covers in jxl, the 64-bit 2.0 version makes no sense due to the lack of almost all plugins.
Sorry for such a long wait for a response.

**Comment by saschanaz** [comment]
Oops! Hmm yeah, that sounds like a pretty valid use case. I'll take a look soon-ish.

**Comment by saschanaz** [comment]
BTW, how should I do to set a JXL cover image on foobar2000? I used it like a decade ago and now I forgot everything 😢

**Comment by Niotferdi** [comment]
Take any music file, put it in a separate folder, and put the jxl-picture "cover.jxl" there.

**Comment by snowbie** [comment]
> BTW, what should I do to set a JXL cover image on foobar2000? I used it like a decade ago and now I forgot everything 😢
go into the file properties and embed the file.

**Comment by Niotferdi** [comment]
So many months have passed, and there is still no 32-bit support. But the only application that needs jxl wic support is 32-bit. If jxl support appears in this 32 bit program, I can save many gigabytes of disk space.

**Comment by Aerocatia** [comment]
I cross-compiled 0.2.3 using the target `i686-pc-windows-gnu` and I can confirm it works fine with the 32-bit version of Foobar2000.

Note that you have to use the 32-bit version of regserv32 that's in SysWOW64.
```
C:\Windows\SysWOW64\regsvr32.exe jxl_winthumb32.dll
```

Here is my (unofficial) build: [jxl_winthumb_0.2.3.zip](https://github.com/saschanaz/jxl-winthumb/files/12709378/jxl_winthumb_0.2.3.zip)

**Comment by somebush** [comment]
Thanks for compiling it for me.
I uploaded the file to virustotal, 11 antiviruses flagged this file as a virus, many complained about Babar.401507. I know there are often false positives, but still. I haven't used the file yet.

**Comment by saschanaz** [comment]
Somehow 64bit dll worked fine on 32bit foobar for me, or maybe I'm doing it wrong? 🤔

**Comment by Aerocatia** [comment]
AV often is like that, It's just the output of the latest tag cross-compiled using Arch Linux rust/mingw-w64.
Cargo is very nice, it is not hard to build this provided you have the environment for it.

**Comment by saschanaz** [comment]
Hmm okay, I tried `rundll32.exe "%ProgramFiles(x86)%\Windows Photo Viewer\PhotoViewer.dll", ImageView_Fullscreen (image path)` to test the build output of `cargo build --release --target i686-pc-windows-msvc` and it works nice. Just posted the result in https://github.com/saschanaz/jxl-winthumb/releases/tag/v0.2.3.

Thanks people and sorry for taking so long time to figure out how to try this.

**Comment by marc2k3** [comment]
I have nothing to do with the devlopement of foobar2000 but I do maintain my own component for it. Its image loading is completely independent of whatever foobar2000 itself does.

Apparently the 64bit jxlthumb has always worked with it but since this 32bit release, I've had this "bug" report...

https://hydrogenaud.io/index.php/topic,110516.msg1034996.html#msg1034996

My code is here...

https://github.com/jscript-panel/Helpers/blob/f5d2c8e1b1ee453c3fe83aa6d03aa136c88451bb/ImageHelpers.cpp#L36-L47

Why should anything be different for 32bit jxl given it supports every other codec thrown at it?

**Comment by saschanaz** [comment]
That's #29, which really needs to be fixed 😞

**Comment by somebush** [comment]
> Apparently the 64bit jxlthumb has always worked with it

Before the release of the 32-bit version with the wic plugin installed, jxl images did not load at all, now they load with distorted (whiter) colors. I don’t understand what I could have done wrong to prevent this plugin from working for me in Foobar2000, whereas it worked for you before.

**Comment by marc2k3** [comment]
Just to be clear, 64bit jxlthumb only worked with 64bit fb2k.
