### ISSUE TITLE
ICC profile in jxl images ignored

### ISSUE THREAD

**Issue by abnormally-distributed** [saschanaz/jxl-winthumb#24]
I saved some images in the JPEG XL format using Affinity Photo 2. I installed jxl-winthumb, and while the images open with Windows Photo Viewer, they are displayed as if they are sRGB encoded. The images are actually in a wider color gamut space, and the ICC profile should be correctly embedded given that if I open the images in Affinity Photo 2 they are in the correct color space. It seems this plugin is having issues with reading or properly utilizing the embedded ICC profile.

**Comment by saschanaz** [comment]
Could you share the images that show the problem? Thanks!

**Comment by VcSaJen** [comment]
@saschanaz sure, here's the link: [https://dl.dropboxusercontent.com/s/pth6ujyfey6sxsx/ICC_profile_JXL.zip](https://dl.dropboxusercontent.com/s/pth6ujyfey6sxsx/ICC_profile_JXL.zip)
![изображение](https://github.com/saschanaz/jxl-winthumb/assets/1311131/57446bf7-9e8d-4530-9a7d-3120641be868)
