### ISSUE TITLE
File Explorer and NeeView incorrectly shows brighter colors

### ISSUE THREAD

**Issue by eddiezato** [saschanaz/jxl-winthumb#29]
[bspv1tbgtep000.jxl.zip](https://github.com/saschanaz/jxl-winthumb/files/12137919/bspv1tbgtep000.jxl.zip) opened with v0.2.0 and v0.1.19:

<img width="308" alt="with_v020" src="https://github.com/saschanaz/jxl-winthumb/assets/11173476/82d39fe2-ac45-444b-9175-b62c057cb220"><img width="308" alt="with_v0119" src="https://github.com/saschanaz/jxl-winthumb/assets/11173476/39d61b05-ccef-4668-b22f-dec8f600e5d1">

[mario_chunli.jxl.zip](https://github.com/saschanaz/jxl-winthumb/files/12137930/mario_chunli.jxl.zip) in NeeView:

<img width="353" alt="with_v020" src="https://github.com/saschanaz/jxl-winthumb/assets/11173476/d779b592-58ea-4d97-a00d-a03edac42103"><img width="353" alt="with_v0119" src="https://github.com/saschanaz/jxl-winthumb/assets/11173476/a73b556e-3b68-485f-972b-8f8c03b8df15">

**Comment by saschanaz** [comment]
The crash problem is https://github.com/tirr-c/jxl-oxide/issues/65. For now let's track only the color space problem here.

The relevant issue is: https://learn.microsoft.com/en-us/windows/win32/wic/-wic-codec-native-pixel-formats#color-space

>In the absence of color space information for an image, the general rule for color space inference is that UINT RGB and grayscale formats use the standard RGB color space (sRGB), while fixed-point and floating-point RGB and grayscale formats use the extended RGB color space (scRGB). The CMYK color model uses an RWOP color space.

jxl-oxide always uses f32 for pixels so I opted to use GUID_WICPixelFormat128bppRGBAFloat, and that defaults to scRGB. GetColorContext somehow solves this for Windows Photo Viewer but not for others e.g. File Explorer, although it does call GetColorContext and its methods. 🤔

**Comment by saschanaz** [comment]
Let me see what Google did here... https://chromium.googlesource.com/webm/libwebp/+/0.4.0/examples/wicdec.c

**Comment by saschanaz** [comment]
Somehow these three lines are enough for Windows Photo Viewer to fix this issue:

https://github.com/saschanaz/jxl-winthumb/blob/47f763f920176931fedd4a12c209aaded3aefcb5/src/lib.rs#L363-L365

But not for others, and those others ignores `InitializeFromExifColorSpace(1)` either. 🤷

**Comment by eddiezato** [comment]
JPEGView shows the same, v0.2.2 and v0.1.19:

<img width="264" alt="022" src="https://github.com/saschanaz/jxl-winthumb/assets/11173476/e13ab105-8979-4465-b252-00740ffbf046"><img width="264" alt="119" src="https://github.com/saschanaz/jxl-winthumb/assets/11173476/63a9699d-e9f0-4487-890b-30c5f1c04841">

**Comment by saschanaz** [comment]
At this point I'd say this is because Microsoft's incomplete WIC implementation in some Windows components. AFAIK those "WIC-supported" image viewers do not use WIC itself but just delegates the API use to the relevant Windows component, which is itself not complete; it can't play animation, can't detect ICC, and doesn't do HDR. Well, Microsoft doesn't do WIC anymore, who would have expected this? 🤷‍♀️ 

I could maybe forget about native ICC support and do some manual color management to convert everything to 32bit integer sRGB, as this issue happens when the library passes colors in 128bit float. But that means giving up HDR while adding more code complexity.

For now my recommendation is to [fall back to Windows Photo Viewer](https://winaero.com/how-to-enable-windows-photo-viewer-in-windows-11/) which still exists in Windows 11 and with better WIC support.

**Comment by Aerocatia** [comment]
Might be worth the complexity given that explorer thumbnails are a primary use-case. Unfortunate.

**Comment by saschanaz** [comment]
Maybe I should finally try [qcms](https://crates.io/crates/qcms)?

**Comment by Aerocatia** [comment]
You could also have cargo specify a git commit for qcms too.

**Comment by saschanaz** [comment]
Sure. It seems qcms doesn't support f64 input that jxl-oxide emits, so the numbers will have to be converted down to u8 before processing ICC (which is not ideal 🤔 but should be sufficient for preview purpose).

**Comment by Ptilopsis01** [comment]
I've met a similar problem that the thumb was abnormally bright, but the windows photo viewer behaves properly.
![image](https://github.com/saschanaz/jxl-winthumb/assets/93318731/c2779252-b877-4e9a-bb04-082c08dba711)

**Comment by Aerocatia** [comment]
It seems jxl-oxide is gaining support for handling the color profiles internally, however no release with this feature has been cut yet.
Perhaps this could solve the issue easily?

**Comment by tirr-c** [comment]
jxl-oxide v0.6.0 (with better color management support) is published. I think now there are three options:
- Enable `lcms2` feature in jxl-oxide and use built-in Little CMS 2 integration. LCMS2 is written in C though.
- Write `ColorManagementSystem` impl for qcms and use it. jxl-oxide will do color management for known color encodings, and delegate rest to qcms. jxl-oxide prefers linear transfer function though, so results might be suboptimal.
- Don't specify any custom color encoding, and do color management separately.

**Comment by saschanaz** [comment]
Rumor says Microsoft is getting WIC support for JXL. Maybe they figured out how to do this correctly with WIC without having to insert external CMS...

**Comment by saschanaz** [comment]
Finally revisiting this. I just confirmed that passing f32 was the culprit, as manually downgrading f32 to u16 just makes things work. It seems somehow for unknown reason WIC cannot process that correctly. Undocumented breakage, GRRRRR

But converting the whole f32 buffer to u16 is kinda expensive and has significant performance impact. I'm doing `let buf: Vec<u16> = buf.iter().map(|n| (*n * u16::MAX as f32) as u16).collect();`, maybe that's not the right way. 😅

**Comment by eddiezato** [comment]
Nice 👍
Looking forward to the next release.

**Comment by eddiezato** [comment]
> Looking forward to the next release.

Never mind. Built it myself. Works fine.
Are these options proper for optimization? Taken from the internet.

```
[profile.release]
debug = false
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
```

**Comment by saschanaz** [comment]
Hmm, good question, I just use [the builtin release profile](https://doc.rust-lang.org/cargo/reference/profiles.html#release). Unsure that other flags matter much here, but lto=true might be useful.

**Comment by Aerocatia** [comment]
`strip = true` is handy for the release profile so you don't have to strip it manually when building the windows-gnu target.

**Comment by eddiezato** [comment]
`strip = true` and `opt-level = 'z'` reduced the size of the dll from 3.5 to 1.34 MiB for me.

**Comment by Aerocatia** [comment]
I don't think we want `opt-level = 'z'`, thumbnail generation speed is more important that a smaller DLL.

**Comment by saschanaz** [comment]
Just added `cargo bench` to do basic performance comparison. Feel free to experiment and see the difference there.
