### ISSUE TITLE
v0.2.x CPU impact

### ISSUE THREAD

**Issue by eddiezato** [saschanaz/jxl-winthumb#38]
I did some testing. You can't call it "testing" though. I was just reading cbz-comics using NeeView. And I noted that the CPU load when decoding images with the latest nightly build of jxl-winthumb is noticeably higher than with v0.1.9. I compared the same files on both dlls.

I understand that there must be differences since v0.2.x did start using jxl-oxide, but I hope there is still room for optimization.

**Comment by saschanaz** [comment]
Dupe of #33? I guess some performance profiling is needed for better investigation.

**Comment by eddiezato** [comment]
Yeah, sorry. I closed it as dupe.
