### ISSUE TITLE
Thumbnails are not generated for some JPEG-XL images.

### ISSUE THREAD

**Issue by Aerocatia** [saschanaz/jxl-winthumb#39]
Issue is in jxl-oxide (or maybe libjxl encoding, hope not)
See: https://github.com/tirr-c/jxl-oxide/issues/268

**Comment by Aerocatia** [comment]
This is fixed by bumping jxl-oxide to 0.7.2

**Comment by saschanaz** [comment]
Released 0.2.5, the image works for me 👍
