### ISSUE TITLE
cpu burn when enable

### ISSUE THREAD

**Issue by raysar** [saschanaz/jxl-winthumb#4]
Hello,
The dll works but it's super slow. And there is some freeze of explorer.
After enable it, the process COM Surrogate take 100% of 1 thread of my cpu, all the time.

![Taskmgr_MIIVIXSafN](https://user-images.githubusercontent.com/6623125/116290580-e9d4ca80-a793-11eb-94e6-2706994b2a22.png)

**Comment by saschanaz** [comment]
I sometimes also see some files cause this, but haven't investigated yet. Could you provide the file that causes this?

**Comment by raysar** [comment]
i don't know, i can kill explorer and com surrogate, process restart  alone and burn.
I have all type of jxl on my folder, maybe with old encoder :D
I switch to the https://github.com/mirillis/jpegxl-wic project, but now i have infinite charging and zero thumbnails, even jpeg png mp4 :D

Could you create a release with the lastest jxl decoder? :D Maybe it works?

**Comment by saschanaz** [comment]
Hmm, I will try that this weekend. If that still doesn't help, then we can put the files into a subfolder one by one so that we can see which specific file is causing issue.

**Comment by raysar** [comment]
Yes i will test it and send you "problematic file"

This command is enought to remove completely the program?
regsvr32 /u jxl_winthumb.dll

**Comment by saschanaz** [comment]
Yup, that command should do the work.

**Comment by saschanaz** [comment]
Note that uninstalling does not unload the dll, and you may need to sign out to actually unload it.

**Comment by saschanaz** [comment]
Just posted a new release, could you check it again?

**Comment by raysar** [comment]
Yes now dll WORKS, you're the best! :p 

Some jxl don't decode, for example, 16 bits files, progressive jxl and file encoded with "--noise 1" (same problem with old chrome canary).

[jxl.zip](https://github.com/saschanaz/jxl-winthumb/files/6421517/jxl.zip)

**Comment by saschanaz** [comment]
Yay, good to hear that!

I see those files decoded on my machine, am I missing something? (Ignore alien.jxl 😀)

![image](https://user-images.githubusercontent.com/3396686/117014183-d922d800-acf0-11eb-9cf9-4e45b917df6d.png)

**Comment by saschanaz** [comment]
Just published another release, please give it a try 😉

**Comment by raysar** [comment]
With your last dll, all jxl display !
Thank you !

**Comment by saschanaz** [comment]
👍👍 Thank you for reporting the issues!
