### ISSUE TITLE
Unable to register current (v0.1.10) and older versions of the DLL

### ISSUE THREAD

**Issue by just-a-user-sudo** [saschanaz/jxl-winthumb#7]
Attempting to register the DLL causes an error. Windows says that it "failed to load." See the below screenshot for more info.

I followed the installation steps as described by downloading the DLL, opening PowerShell as an administrator, moving the DLL to my Downloads folder, and inputting `cd C:\Users\[username]\Downloads` and `regsvr32 jxl_winthumb.dll` into PowerShell.

This error shouldn't occur to my knowledge, and my laptop should start being able to start loading thumbnails for JXLs.

![Screenshot (1)](https://user-images.githubusercontent.com/80051348/125329906-948d6b80-e335-11eb-8bdb-b29dbb468cc3.png)

***

I've attempted this on three different Windows installations, and two of them run into this issue. The first attempt was on an Acer Nitro 5 (AN515-54) running Windows 10 Home, and has v0.1.7 registered. It works as expected. The second attempt was v0.1.10 on a HP Pavilion x360 Convertible (14m-dh0xxx) running Windows 10 Enterprise LTSC March 2019. It did not work and ran into the error described above. The third attempt was v0.1.10 on the same HP convertible, running Windows 10 Enterprise. It did not work and ran into the error described above.

***

Troubleshooting I tried:

* Tried to register v0.1.7 on the HP
* Tried registering the DLL in different folders, including System32 and SysWOW64
* Tried using Admin Command Prompt instead of Admin PowerShell
* Updated the HP to the latest software and drivers, including optional features
* Tried registering with and without "HEIF Image Extensions," "Web Media Extensions," and "Webp Image Extensions" installed on the Enterprise installation
* Turned the HP off and on

If there are dependencies that are actually missing, I'm at a loss for what they could be. Though, I'm glad the DLL works on one of my laptops and I do find it useful.

**Comment by saschanaz** [comment]
Does 0.1.10 also work on the Acer machine? 🤔

**Comment by just-a-user-sudo** [comment]
Yes. It was able to register and I confirmed that it can make thumbnails some new JXLs.
![Export](https://user-images.githubusercontent.com/80051348/125342381-619ea400-e344-11eb-9215-5fc9fa682f82.png)

**Comment by saschanaz** [comment]
Hmm, could you try installing [Microsoft Visual C++ Redistributable for Visual Studio 2019](https://visualstudio.microsoft.com/downloads/#microsoft-visual-c-redistributable-for-visual-studio-2019) and try again?

**Comment by just-a-user-sudo** [comment]
Sure. I want to download the tools necessary and use locally. What workloads and/or individual components should I install if I wanna keep it minimal? Below is a list of the preset workloads.

<img width="536" alt="Screenshot (5)" src="https://user-images.githubusercontent.com/80051348/125350886-ef7f8c80-e34e-11eb-93bc-ab2d96921f9a.png">

I mean, I don't know what to pick. If you're not sure either then I could just try installing different workloads and see what works.

**Comment by saschanaz** [comment]
Oh no, you are installing the full Visual Studio. The page has a much smaller one called as what I just said.

**Comment by just-a-user-sudo** [comment]
Oh, I had JavaScript disabled initially so I didn't see it. I've installed Visual C++ Redistributable and tried registering the DLL again and it works now! Thank you for the help.

**Comment by saschanaz** [comment]
Thanks for your reporting! I'll have to mention that dependency then 👍
